services:
  - type: web
    name: render-chat-listener
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread -b 0.0.0.0:$PORT app:app
    envVars:
      - key: BOT_REGION
        value: BD
